 export const MoviesData = 
 [
  {
            "id": "1",
            "idi": 1008005,
            "title": "The Communion Girl",
            "language": "es",
            "overview": "Spain, late 1980s. Newcomer Sara tries to fit in with the other teens in this tight-knit small town in the province of Tarragona. If only she were more like her extroverted best friend, Rebe. They go out one night at a nightclub, on the way home",
            "image": "https://image.tmdb.org/t/p/original/sP6AO11a7jWgsmT9T8j9EGIWAaZ.jpg",
            "date": "2023-02-10",
            "background": "https://image.tmdb.org/t/p/original/54IXMMEQKlkPXHqPExWy98UBmtE.jpg",
            "gender": "Terror"
        },
        {
            "id": "2",
            "idi": 758323,
            "title": "The Pope's Exorcist",
            "language": "en",
            "overview": "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
            "image": "https://image.tmdb.org/t/p/original/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg",
            "date": "2023-04-05",
            "background": "https://image.tmdb.org/t/p/original/5Y5pz0NX7SZS9036I733F7uNcwK.jpg",
            "gender": "Terror"
        },
        {
            "id": "3",
            "idi": 980078,
            "title": "Winnie the Pooh: Blood and Honey",
            "language": "en",
            "overview": "Christopher Robin is headed off to college and he has abandoned his old friends, Pooh and Piglet, which then leads to the duo embracing their inner monsters.",
            "image": "https://image.tmdb.org/t/p/original/ewF3IlGscc7FjgGEPcQvZsAsgAW.jpg",
            "date": "2023-01-27",
            "background": "https://image.tmdb.org/t/p/original/wD2kUCX1Bb6oeIb2uz7kbdfLP6k.jpg",
            "gender": "Terror"
        },
        {
            "id": "5",
            "idi": 1084225,
            "title": "The Park",
            "language": "en",
            "overview": "A dystopian coming-of-age movie focused on three kids who find themselves in an abandoned amusement park, aiming to unite whoever remains. With dangers lurking around every corner, they will do whatever it takes to survive their hellish Neverlan",
            "image": "https://image.tmdb.org/t/p/original/hR1jdCw0A9czgsbp45TASkjjBhA.jpg",
            "date": "2023-03-02",
            "background": "https://image.tmdb.org/t/p/original/cevmHkKqSlrTYqpJ5eaAjml1jec.jpg",
            "gender": "Terror"
        },
        {
            "id": "4",
            "idi": 713704,
            "title": "Evil Dead Rise",
            "language": "en",
            "overview": "Two sisters find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
            "image": "https://image.tmdb.org/t/p/original/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg",
            "date": "2023-04-12",
            "background": "https://image.tmdb.org/t/p/original/7bWxAsNPv9CXHOhZbJVlj2KxgfP.jpg",
            "gender": "Terror"
        },
        {
            "id": "6",
            "idi": 296271,
            "title": "The Devil Conspiracy",
            "language": "en",
            "overview": "The hottest biotech company in the world has discovered they can clone history’s most influential people from the dead. Now, they are auctioning clones of Michelangelo, Galileo, Vivaldi, and others for tens of millions of dollars to the world’s ",
            "image": "https://image.tmdb.org/t/p/original/2lUYbD2C3XSuwqMUbDVDQuz9mqz.jpg",
            "date": "2023-01-13",
            "background": "https://image.tmdb.org/t/p/original/sp7MPK2K60LLd7A6zjHKsfgjFil.jpg",
            "gender": "Terror"
        },
        {
            "id": "7",
            "idi": 1023313,
            "title": "The Exorcist",
            "language": "es",
            "overview": "Ophelia, a young nun recently arriving in the town of San Ramon, is forced to perform an exorcism on a pregnant woman in danger of dying. Just when she thinks her possession has ended, she discovers that the evil presence hasn't disappeared yet.",
            "image": "https://image.tmdb.org/t/p/original/d07xtqwq1uriQ1hda6qeu8Skt5m.jpg",
            "date": "2022-11-02",
            "background": "https://image.tmdb.org/t/p/original/u5nY7pY2Y58o7dSM9cy6NclOV8V.jpg",
            "gender": "Terror"
        },
        {
            "id": "8",
            "idi": 536554,
            "title": "M3GAN",
            "language": "en",
            "overview": "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her ne",
            "image": "https://image.tmdb.org/t/p/original/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg",
            "date": "2022-12-28",
            "background": "https://image.tmdb.org/t/p/original/dlrWhn0G3AtxYUx2D9P2bmzcsvF.jpg",
            "gender": "Terror"
        },
        {
            "id": "9",
            "idi": 631842,
            "title": "Knock at the Cabin",
            "language": "en",
            "overview": "While vacationing at a remote cabin, a young girl and her two fathers are taken hostage by four armed strangers who demand that the family make an unthinkable choice to avert the apocalypse. With limited access to the outside world, the family m",
            "image": "https://image.tmdb.org/t/p/original/dm06L9pxDOL9jNSK4Cb6y139rrG.jpg",
            "date": "2023-02-01",
            "background": "https://image.tmdb.org/t/p/original/zM9RGbJBZ3UNpFOabcRqh0iVAYP.jpg",
            "gender": "Terror"
        },
        {
            "id": "10",
            "idi": 1073413,
            "title": "Phenomena",
            "language": "es",
            "overview": "Madrid, Spain, 1998. The many resources and skills of Gloria, Paz and Sagrario, three middle-aged women investigating paranormal events, are put to the test when their leader, Father Pilón, has an unpleasant encounter.",
            "image": "https://image.tmdb.org/t/p/original/liosTyTUf0ObasR2HLTOrHQlzth.jpg",
            "date": "2023-04-14",
            "background": "https://image.tmdb.org/t/p/original/qE3QIUTvoAeZZlCv0xlxFhsVMPE.jpg",
            "gender": "Terror"
        },
        {
            "id": "11",
            "idi": 984105,
            "title": "The Mummy Resurrection",
            "language": "en",
            "overview": "When an infamous \"cursed\" Egyptian sarcophagus falls into the hands of unscrupulous huckster Everett Randolph, he becomes obsessed with resurrecting the mummified princess held within it.",
            "image": "https://image.tmdb.org/t/p/original/d0pt6KlVvmtG0uhccWjgWfIqJee.jpg",
            "date": "2023-01-02",
            "background": "https://image.tmdb.org/t/p/original/o6PcqdeWMhvDGSkbzgKNfnzd2Js.jpg",
            "gender": "Terror"
        },
        {
            "id": "12",
            "idi": 109428,
            "title": "Evil Dead",
            "language": "en",
            "overview": "Five young friends find the mysterious and fiercely powerful Book of the Dead, and unable to resist its temptation, release a violent demon on a bloodthirsty quest to possess them all.",
            "image": "https://image.tmdb.org/t/p/original/1gDV0Lm9y8ufIKzyf0h0GBgb9Zj.jpg",
            "date": "2013-04-05",
            "background": "https://image.tmdb.org/t/p/original/c0rYFlL76pAg6zExn0etOWOofjr.jpg",
            "gender": "Terror"
        },
        {
            "id": "13",
            "idi": 1011679,
            "title": "Shark Side of the Moon",
            "language": "en",
            "overview": "Decades ago, the USSR developed unkillable sharks and launched them to the moon. Today, a team of American astronauts will endure the fight of their lives.",
            "image": "https://image.tmdb.org/t/p/original/v5CfpzxoJDkZxjZAizClFdlEF0U.jpg",
            "date": "2022-08-12",
            "background": "https://image.tmdb.org/t/p/original/AsEgGeccI32SwMBkxpwhOkhbzmF.jpg",
            "gender": "Terror"
        },
        {
            "id": "14",
            "idi": 1003579,
            "title": "Batman: The Doom That Came to Gotham",
            "language": "en",
            "overview": "Explorer Bruce Wayne accidentally unleashes an ancient evil, and returns to Gotham after being away for two decades. There, Batman battles Lovecraftian supernatural forces and encounters allies and enemies such as Green Arrow, Ra's al Ghul, Mr. ",
            "image": "https://image.tmdb.org/t/p/original/v0Jsn4jSN4yUBbKoVNCU7Zuzl1U.jpg",
            "date": "2023-03-10",
            "background": "https://image.tmdb.org/t/p/original/7eccX0xay9pDj6ZQvU4cu3whw18.jpg",
            "gender": "Terror"
        },
        {
            "id": "15",
            "idi": 934433,
            "title": "Scream VI",
            "language": "en",
            "overview": "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.",
            "image": "https://image.tmdb.org/t/p/original/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg",
            "date": "2023-03-08",
            "background": "https://image.tmdb.org/t/p/original/44immBwzhDVyjn87b3x3l9mlhAD.jpg",
            "gender": "Terror"
        },
        {
            "id": "16",
            "idi": 884184,
            "title": "Consecration",
            "language": "en",
            "overview": "After the alleged suicide of her priest brother, Grace travels to the remote Scottish convent where he fell to his death. Distrusting the Church's account, she uncovers murder, sacrilege and a disturbing truth about herself.",
            "image": "https://image.tmdb.org/t/p/original/yQTRmPzKAdLodknnPVtImm6FWPZ.jpg",
            "date": "2023-02-09",
            "background": "https://image.tmdb.org/t/p/original/sRfX2XPjyL7nRKVRKXVG6D0bVQI.jpg",
            "gender": "Terror"
        },
        {
            "id": "17",
            "idi": 1026563,
            "title": "13 Exorcisms",
            "language": "es",
            "overview": "After participating in a séance, young Laura begins to behave strangely. Alarmed, her parents ask Father Olmedo, one of the few exorcists authorized by the Vatican to intervene in cases of demonic possession, for help.",
            "image": "https://image.tmdb.org/t/p/original/8LpnMIqpRiwxpbGR33ALCmVl7gj.jpg",
            "date": "2022-11-04",
            "background": "https://image.tmdb.org/t/p/original/2E6pIbJien7B9yWpaz8Yd2njzUI.jpg",
            "gender": "Terror"
        },
        {
            "id": "18",
            "idi": 676547,
            "title": "Prey for the Devil",
            "language": "en",
            "overview": "In response to a global rise in demonic possessions, the Catholic Church reopens exorcism schools to train priests in the Rite of Exorcism. On this spiritual battlefield, an unlikely warrior rises: a young nun, Sister Ann. Thrust onto the spirit",
            "image": "https://image.tmdb.org/t/p/original/iCvgemXf2Kpr2LvpDmt5J9NhjKM.jpg",
            "date": "2022-10-23",
            "background": "https://image.tmdb.org/t/p/original/94kQGMiFbs5MUTlt7kj9dewsMDi.jpg",
            "gender": "Terror"
        },
        {
            "id": "19",
            "idi": 646385,
            "title": "Scream",
            "language": "en",
            "overview": "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
            "image": "https://image.tmdb.org/t/p/original/4qIV5WXP1xQvpPAHmgVxCmxvPh6.jpg",
            "date": "2022-01-12",
            "background": "https://image.tmdb.org/t/p/original/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
            "gender": "Terror"
        },
        {
            "id": "20",
            "idi": 988165,
            "title": "H.P. Lovecraft's Witch House",
            "language": "en",
            "overview": "Determined to prove the possibility of alternate dimensions, a graduate student unknowingly unlocks a gateway to unimaginable horror. Based on the H.P. Lovecraft's short story The Dreams in the Witch House.",
            "image": "https://image.tmdb.org/t/p/original/5KmscR49WkmuPJKjmK4OUmsRn5C.jpg",
            "date": "2022-06-29",
            "background": "https://image.tmdb.org/t/p/original/7cjY1IIrW1RwmHN8USPryKTAQHq.jpg",
            "gender": "Terror"
        },
        {
            "id": "21",
            "idi": 640146,
            "title": "Ant-Man and the Wasp: Quantumania",
            "language": "en",
            "overview": "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on ",
            "image": "https://image.tmdb.org/t/p/original/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
            "date": "2023-02-15",
            "background": "https://image.tmdb.org/t/p/original/8YFL5QQVPy3AgrEQxNYVSgiPEbe.jpg",
            "gender": "Action"
        },
        {
            "id": "22",
            "idi": 594767,
            "title": "Shazam! Fury of the Gods",
            "language": "en",
            "overview": "Billy Batson and his foster siblings, who transform into superheroes by saying \"Shazam!\", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.",
            "image": "https://image.tmdb.org/t/p/original/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg",
            "date": "2023-03-15",
            "background": "https://image.tmdb.org/t/p/original/nDxJJyA5giRhXx96q1sWbOUjMBI.jpg",
            "gender": "Action"
        },
        {
            "id": "23",
            "idi": 76600,
            "title": "Avatar: The Way of Water",
            "language": "en",
            "overview": "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and",
            "image": "https://image.tmdb.org/t/p/original/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
            "date": "2022-12-14",
            "background": "https://image.tmdb.org/t/p/original/ovM06PdF3M8wvKb06i4sjW3xoww.jpg",
            "gender": "Action"
        },
        {
            "id": "24",
            "idi": 948713,
            "title": "The Last Kingdom: Seven Kings Must Die",
            "language": "en",
            "overview": "In the wake of King Edward's death, Uhtred of Bebbanburg and his comrades adventure across a fractured kingdom in the hopes of uniting England at last.",
            "image": "https://image.tmdb.org/t/p/original/7yyFEsuaLGTPul5UkHc5BhXnQ0k.jpg",
            "date": "2023-04-14",
            "background": "https://image.tmdb.org/t/p/original/xwA90BwZXTh8ke3CVsQlj8EOkFr.jpg",
            "gender": "Action"
        },
        {
            "id": "25",
            "idi": 677179,
            "title": "Creed III",
            "language": "en",
            "overview": "After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damian Anderson, resurfaces after serving a long sentence in prison, he is eager to prove th",
            "image": "https://image.tmdb.org/t/p/original/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg",
            "date": "2023-03-01",
            "background": "https://image.tmdb.org/t/p/original/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg",
            "gender": "Action"
        },
        {
            "id": "26",
            "idi": 638974,
            "title": "Murder Mystery 2",
            "language": "en",
            "overview": "After starting their own detective agency, Nick and Audrey Spitz land a career-making case when their billionaire pal is kidnapped from his wedding.",
            "image": "https://image.tmdb.org/t/p/original/s1VzVhXlqsevi8zeCMG9A16nEUf.jpg",
            "date": "2023-03-28",
            "background": "https://image.tmdb.org/t/p/original/bT3IpP7OopgiVuy6HCPOWLuaFAd.jpg",
            "gender": "Action"
        },
        {
            "id": "27",
            "idi": 603692,
            "title": "John Wick: Chapter 4",
            "language": "en",
            "overview": "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old frien",
            "image": "https://image.tmdb.org/t/p/original/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
            "date": "2023-03-22",
            "background": "https://image.tmdb.org/t/p/original/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
            "gender": "Action"
        },
        {
            "id": "28",
            "idi": 946310,
            "title": "Pirates Down the Street II: The Ninjas from Across",
            "language": "nl",
            "overview": "The pirates feel right at home in Sandborough, but the atmosphere cools right down when the ninjas come to live in the street. After all, pirates and ninjas are sworn enemies!  While pirate captain Hector Blunderbuss struggles to get rid of his ",
            "image": "https://image.tmdb.org/t/p/original/uDsvma9dAwnDPVuCFi99YpWvBk0.jpg",
            "date": "2022-04-20",
            "background": "https://image.tmdb.org/t/p/original/tFaC1Fb1sv1dALB0i9Avi76MHmn.jpg",
            "gender": "Action"
        },
        {
            "id": "29",
            "idi": 700391,
            "title": "65",
            "language": "en",
            "overview": "65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth must fend off dinosaurs and reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.",
            "image": "https://image.tmdb.org/t/p/original/rzRb63TldOKdKydCvWJM8B6EkPM.jpg",
            "date": "2023-03-02",
            "background": "https://image.tmdb.org/t/p/original/eSVu1FvGPy86TDo4hQbpuHx55DJ.jpg",
            "gender": "Action"
        },
        {
            "id": "30",
            "idi": 849869,
            "title": "Kill Boksoon",
            "language": "ko",
            "overview": "At work, she's a renowned assassin. At home, she's a single mom to a teenage daughter. Killing? That's easy. It's parenting that's the hard part.",
            "image": "https://image.tmdb.org/t/p/original/taYgn3RRpCGlTGdaGQvnSIOzXFy.jpg",
            "date": "2023-02-17",
            "background": "https://image.tmdb.org/t/p/original/tYcmm8XtzRdcT6kliCbHuWwLCwB.jpg",
            "gender": "Action"
        },
        {
            "id": "31",
            "idi": 842945,
            "title": "Supercell",
            "language": "en",
            "overview": "Good-hearted teenager William always lived in hope of following in his late father’s footsteps and becoming a storm chaser. His father’s legacy has now been turned into a storm-chasing tourist business, managed by the greedy and reckless Zane Ro",
            "image": "https://image.tmdb.org/t/p/original/gbGHezV6yrhua0KfAgwrknSOiIY.jpg",
            "date": "2023-03-17",
            "background": "https://image.tmdb.org/t/p/original/m1fgGSLK0WvRpzM1AmZu38m0Tx8.jpg",
            "gender": "Action"
        },
        {
            "id": "32",
            "idi": 1033219,
            "title": "Attack on Titan",
            "language": "en",
            "overview": "As viable water is depleted on Earth, a mission is sent to Saturn's moon Titan to retrieve sustainable H2O reserves from its alien inhabitants. But just as the humans acquire the precious resource, they are attacked by Titan rebels, who don't tr",
            "image": "https://image.tmdb.org/t/p/original/qNz4l8UgTkD8rlqiKZ556pCJ9iO.jpg",
            "date": "2022-09-30",
            "background": "https://image.tmdb.org/t/p/original/eNJhWy7xFzR74SYaSJHqJZuroDm.jpg",
            "gender": "Action"
        },
        {
            "id": "33",
            "idi": 1048300,
            "title": "Adrenaline",
            "language": "en",
            "overview": "A female FBI agent holidaying in Eastern Europe with her family gets her life upside down when her daughter is kidnapped. She has to team up with a criminal on the run to save her daughter before time runs out.",
            "image": "https://image.tmdb.org/t/p/original/qVzRt8c2v4gGBYsnaflXVVeQ9Lh.jpg",
            "date": "2022-12-15",
            "background": "https://image.tmdb.org/t/p/original/nDmPjKLqLwWyd4Ssti8HCdhW5cZ.jpg",
            "gender": "Action"
        },
        {
            "id": "34",
            "idi": 505642,
            "title": "Black Panther: Wakanda Forever",
            "language": "en",
            "overview": "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with ",
            "image": "https://image.tmdb.org/t/p/original/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
            "date": "2022-11-09",
            "background": "https://image.tmdb.org/t/p/original/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
            "gender": "Action"
        },
        {
            "id": "35",
            "idi": 1084225,
            "title": "The Park",
            "language": "en",
            "overview": "A dystopian coming-of-age movie focused on three kids who find themselves in an abandoned amusement park, aiming to unite whoever remains. With dangers lurking around every corner, they will do whatever it takes to survive their hellish Neverlan",
            "image": "https://image.tmdb.org/t/p/original/hR1jdCw0A9czgsbp45TASkjjBhA.jpg",
            "date": "2023-03-02",
            "background": "https://image.tmdb.org/t/p/original/cevmHkKqSlrTYqpJ5eaAjml1jec.jpg",
            "gender": "Action"
        },
        {
            "id": "36",
            "idi": 436270,
            "title": "Black Adam",
            "language": "en",
            "overview": "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
            "image": "https://image.tmdb.org/t/p/original/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
            "date": "2022-10-19",
            "background": "https://image.tmdb.org/t/p/original/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg",
            "gender": "Action"
        },
        {
            "id": "37",
            "idi": 646389,
            "title": "Plane",
            "language": "en",
            "overview": "After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.",
            "image": "https://image.tmdb.org/t/p/original/qi9r5xBgcc9KTxlOLjssEbDgO0J.jpg",
            "date": "2023-01-12",
            "background": "https://image.tmdb.org/t/p/original/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg",
            "gender": "Action"
        },
        {
            "id": "38",
            "idi": 850871,
            "title": "Sayen",
            "language": "es",
            "overview": "Sayen is hunting down the men who murdered her grandmother. Using her training and knowledge of nature, she is able to turn the tables on them, learning of a conspiracy from a corporation that threatens her people's ancestral lands.",
            "image": "https://image.tmdb.org/t/p/original/aCy61aU7BMG7SfhkaAaasS0KzUO.jpg",
            "date": "2023-03-03",
            "background": "https://image.tmdb.org/t/p/original/muw9YsAsSd3DDRme2OEJJoVqun9.jpg",
            "gender": "Action"
        },
        {
            "id": "39",
            "idi": 758009,
            "title": "Shotgun Wedding",
            "language": "en",
            "overview": "Darcy and Tom gather their families for the ultimate destination wedding but when the entire party is taken hostage, “’Til Death Do Us Part” takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save t",
            "image": "https://image.tmdb.org/t/p/original/t79ozwWnwekO0ADIzsFP1E5SkvR.jpg",
            "date": "2022-12-28",
            "background": "https://image.tmdb.org/t/p/original/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg",
            "gender": "Action"
        },
        {
            "id": "40",
            "idi": 385687,
            "title": "Fast X",
            "language": "en",
            "overview": "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the s",
            "image": "https://image.tmdb.org/t/p/original/jwMMQR69Xz9AYtX4u2uYJgfAAev.jpg",
            "date": "2023-05-17",
            "background": "https://image.tmdb.org/t/p/original/fI5RsaM0NSU6TqztRhA2pal5ezv.jpg",
            "gender": "Action"
        },
        {
            "id": "41",
            "idi": 502356,
            "title": "The Super Mario Bros. Movie",
            "language": "en",
            "overview": "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find",
            "image": "https://image.tmdb.org/t/p/original/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
            "date": "2023-04-05",
            "background": "https://image.tmdb.org/t/p/original/iJQIbOPm81fPEGKt5BPuZmfnA54.jpg",
            "gender": "Comedy"
        },
        {
            "id": "42",
            "idi": 594767,
            "title": "Shazam! Fury of the Gods",
            "language": "en",
            "overview": "Billy Batson and his foster siblings, who transform into superheroes by saying \"Shazam!\", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.",
            "image": "https://image.tmdb.org/t/p/original/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg",
            "date": "2023-03-15",
            "background": "https://image.tmdb.org/t/p/original/nDxJJyA5giRhXx96q1sWbOUjMBI.jpg",
            "gender": "Comedy"
        },
        {
            "id": "43",
            "idi": 638974,
            "title": "Murder Mystery 2",
            "language": "en",
            "overview": "After starting their own detective agency, Nick and Audrey Spitz land a career-making case when their billionaire pal is kidnapped from his wedding.",
            "image": "https://image.tmdb.org/t/p/original/s1VzVhXlqsevi8zeCMG9A16nEUf.jpg",
            "date": "2023-03-28",
            "background": "https://image.tmdb.org/t/p/original/bT3IpP7OopgiVuy6HCPOWLuaFAd.jpg",
            "gender": "Comedy"
        },
        {
            "id": "44",
            "idi": 315162,
            "title": "Puss in Boots: The Last Wish",
            "language": "en",
            "overview": "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine l",
            "image": "https://image.tmdb.org/t/p/original/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
            "date": "2022-12-07",
            "background": "https://image.tmdb.org/t/p/original/ouB7hwclG7QI3INoYJHaZL4vOaa.jpg",
            "gender": "Comedy"
        },
        {
            "id": "45",
            "idi": 804150,
            "title": "Cocaine Bear",
            "language": "en",
            "overview": "Inspired by a true story, an oddball group of cops, criminals, tourists and teens converge in a Georgia forest where a 500-pound black bear goes on a murderous rampage after unintentionally ingesting cocaine.",
            "image": "https://image.tmdb.org/t/p/original/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg",
            "date": "2023-02-22",
            "background": "https://image.tmdb.org/t/p/original/a2tys4sD7xzVaogPntGsT1ypVoT.jpg",
            "gender": "Comedy"
        },
        {
            "id": "46",
            "idi": 816904,
            "title": "Mummies",
            "language": "es",
            "overview": "Through a series of unfortunate events, three mummies end up in present-day London and embark on a wacky and hilarious journey in search of an old ring belonging to the Royal Family, stolen by ambitious archaeologist Lord Carnaby.",
            "image": "https://image.tmdb.org/t/p/original/qVdrYN8qu7xUtsdEFeGiIVIaYd.jpg",
            "date": "2023-01-05",
            "background": "https://image.tmdb.org/t/p/original/c3hl9E8E7b9opXDFVF5tSyk0ykr.jpg",
            "gender": "Comedy"
        },
        {
            "id": "47",
            "idi": 869626,
            "title": "Marcel the Shell with Shoes On",
            "language": "en",
            "overview": "Marcel is an adorable one-inch-tall shell who ekes out a colorful existence with his grandmother Connie and their pet lint, Alan. Once part of a sprawling community of shells, they now live alone as the sole survivors of a mysterious tragedy. Bu",
            "image": "https://image.tmdb.org/t/p/original/jaYmP4Ct8YLnxWAW2oYkUjeXtzm.jpg",
            "date": "2022-06-24",
            "background": "https://image.tmdb.org/t/p/original/1PRWW60yQparK1I8Soyy9Evf7Dv.jpg",
            "gender": "Comedy"
        },
        {
            "id": "48",
            "idi": 536554,
            "title": "M3GAN",
            "language": "en",
            "overview": "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her ne",
            "image": "https://image.tmdb.org/t/p/original/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg",
            "date": "2022-12-28",
            "background": "https://image.tmdb.org/t/p/original/dlrWhn0G3AtxYUx2D9P2bmzcsvF.jpg",
            "gender": "Comedy"
        },
        {
            "id": "49",
            "idi": 676710,
            "title": "The Amazing Maurice",
            "language": "en",
            "overview": "Maurice is a streetwise ginger cat who comes up with a money-making scam by befriending a group of self-taught talking rats. When Maurice and the rodents meet a bookworm called Malicia, their little con soon goes down the drain.",
            "image": "https://image.tmdb.org/t/p/original/ydhZeUjbzVEFclUpMhLfDZSavUY.jpg",
            "date": "2022-12-16",
            "background": "https://image.tmdb.org/t/p/original/70aVSo3fuZ94jyQ3rT64afEf8lV.jpg",
            "gender": "Comedy"
        },
        {
            "id": "50",
            "idi": 676841,
            "title": "Unhappily Ever After",
            "language": "es",
            "overview": "María José and Alfredo are about to celebrate their 20th anniversary and their children give them a trip to the hotel where they celebrated their honeymoon, but a spell will make them repeat the same day.",
            "image": "https://image.tmdb.org/t/p/original/qiAM7Y8xF8wJDDsjeSuLgzyFGmd.jpg",
            "date": "2023-01-26",
            "background": "https://image.tmdb.org/t/p/original/9EIUIgBYzGra7Xxemgs8JB049si.jpg",
            "gender": "Comedy"
        },
        {
            "id": "51",
            "idi": 1073413,
            "title": "Phenomena",
            "language": "es",
            "overview": "Madrid, Spain, 1998. The many resources and skills of Gloria, Paz and Sagrario, three middle-aged women investigating paranormal events, are put to the test when their leader, Father Pilón, has an unpleasant encounter.",
            "image": "https://image.tmdb.org/t/p/original/liosTyTUf0ObasR2HLTOrHQlzth.jpg",
            "date": "2023-04-14",
            "background": "https://image.tmdb.org/t/p/original/qE3QIUTvoAeZZlCv0xlxFhsVMPE.jpg",
            "gender": "Comedy"
        },
        {
            "id": "52",
            "idi": 758009,
            "title": "Shotgun Wedding",
            "language": "en",
            "overview": "Darcy and Tom gather their families for the ultimate destination wedding but when the entire party is taken hostage, “’Til Death Do Us Part” takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save t",
            "image": "https://image.tmdb.org/t/p/original/t79ozwWnwekO0ADIzsFP1E5SkvR.jpg",
            "date": "2022-12-28",
            "background": "https://image.tmdb.org/t/p/original/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg",
            "gender": "Comedy"
        },
        {
            "id": "53",
            "idi": 1101799,
            "title": "Queens on the Run",
            "language": "es",
            "overview": "When four women finally take the road trip they planned in high school, they have no idea of the things they'll bump into sometimes literally.",
            "image": "https://image.tmdb.org/t/p/original/oUmuwUIofGsgOr05kieD3Q8ELEO.jpg",
            "date": "2023-04-14",
            "background": "https://image.tmdb.org/t/p/original/ttXABm22Vu9MsQjDAF3Lx2nUPy0.jpg",
            "gender": "Comedy"
        },
        {
            "id": "54",
            "idi": 868759,
            "title": "Ghosted",
            "language": "en",
            "overview": "Salt-of-the-earth Cole falls head over heels for enigmatic Sadie — but then makes the shocking discovery that she’s a secret agent. Before they can decide on a second date, Cole and Sadie are swept away on an international adventure to save the ",
            "image": "https://image.tmdb.org/t/p/original/liLN69YgoovHVgmlHJ876PKi5Yi.jpg",
            "date": "2023-04-21",
            "background": "https://image.tmdb.org/t/p/original/b9UCfDzwiWw7mIFsIQR9ZJUeh7q.jpg",
            "gender": "Comedy"
        },
        {
            "id": "55",
            "idi": 1077280,
            "title": "Die Hart",
            "language": "en",
            "overview": "Kevin Hart - playing a version of himself - is on a death-defying quest to become an action star. And with a little help from John Travolta, Nathalie Emmanuel, and Josh Hartnett - he just might pull it off.",
            "image": "https://image.tmdb.org/t/p/original/1EnBjTJ5utgT1OXYBZ8YwByRCzP.jpg",
            "date": "2023-02-22",
            "background": "https://image.tmdb.org/t/p/original/pxJbfnMIQQxCrdeLD0zQnWr6ouL.jpg",
            "gender": "Comedy"
        },
        {
            "id": "56",
            "idi": 668482,
            "title": "Roald Dahl's Matilda the Musical",
            "language": "en",
            "overview": "An extraordinary young girl discovers her superpower and summons the remarkable courage, against all odds, to help others change their stories, whilst also taking charge of her own destiny. Standing up for what's right, she's met with miraculous",
            "image": "https://image.tmdb.org/t/p/original/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg",
            "date": "2022-11-25",
            "background": "https://image.tmdb.org/t/p/original/nWs0auTqn2UaFGfTKtUE5tlTeBu.jpg",
            "gender": "Comedy"
        },
        {
            "id": "57",
            "idi": 616037,
            "title": "Thor: Love and Thunder",
            "language": "en",
            "overview": "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. ",
            "image": "https://image.tmdb.org/t/p/original/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
            "date": "2022-07-06",
            "background": "https://image.tmdb.org/t/p/original/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg",
            "gender": "Comedy"
        },
        {
            "id": "58",
            "idi": 675353,
            "title": "Sonic the Hedgehog 2",
            "language": "en",
            "overview": "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations",
            "image": "https://image.tmdb.org/t/p/original/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
            "date": "2022-04-08",
            "background": "https://image.tmdb.org/t/p/original/yEQqrW61rwNuVRHTjgHOAU4dXNE.jpg",
            "gender": "Comedy"
        },
        {
            "id": "59",
            "idi": 1058732,
            "title": "The Simpsons Meet the Bocellis in Feliz Navidad",
            "language": "en",
            "overview": "This Christmas, Homer surprises Marge with the ultimate gift: an unforgettable performance from Italian opera superstar Andrea Bocelli and his children Matteo and Virginia.",
            "image": "https://image.tmdb.org/t/p/original/9rJFKvYvSyQ3HoTl1gcU55FOzYi.jpg",
            "date": "2022-12-15",
            "background": "https://image.tmdb.org/t/p/original/9j0V8Fw5u4cv9cESUXUmTGmpXU5.jpg",
            "gender": "Comedy"
        },
        {
            "id": "60",
            "idi": 947938,
            "title": "Dolphin Boy",
            "language": "ru",
            "overview": "When a plane crashes at sea, dolphins rescue a little boy and raise him as family. He lives a carefree life beneath the waves until an evil monster seizes power over the underwater world. The boy is banished to dry land, where a kind-hearted cap",
            "image": "https://image.tmdb.org/t/p/original/gISoDEiaUH9BNEunmLC7FgUVaia.jpg",
            "date": "2022-04-07",
            "background": "https://image.tmdb.org/t/p/original/vXjpwkXPirBmgdEpIknfN8ziDD.jpg",
            "gender": "Comedy"
        },
        {
            "id": "61",
            "idi": 603692,
            "title": "John Wick: Chapter 4",
            "language": "en",
            "overview": "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old frien",
            "image": "https://image.tmdb.org/t/p/original/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
            "date": "2023-03-22",
            "background": "https://image.tmdb.org/t/p/original/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
            "gender": "Crime"
        },
        {
            "id": "62",
            "idi": 877703,
            "title": "Teen Wolf: The Movie",
            "language": "en",
            "overview": "The wolves are howling once again, as a terrifying ancient evil emerges in Beacon Hills. Scott McCall, no longer a teenager yet still an Alpha, must gather new allies and reunite trusted friends to fight back against this powerful and deadly ene",
            "image": "https://image.tmdb.org/t/p/original/wAkpPm3wcHRqZl8XjUI3Y2chYq2.jpg",
            "date": "2023-01-18",
            "background": "https://image.tmdb.org/t/p/original/96SADhPnkXnVN3KaRKsDeBovLcm.jpg",
            "gender": "TV"
        },
        {
            "id": "63",
            "idi": 755812,
            "title": "Miraculous World: New York, United HeroeZ",
            "language": "fr",
            "overview": "Teen Parisian superheroes Ladybug and Chat Noir visit New York on a field trip and discover that superheroes exist in the United States too.",
            "image": "https://image.tmdb.org/t/p/original/9YbyvcrHmY2SVbdfXpb8mC4Fy0g.jpg",
            "date": "2020-12-18",
            "background": "https://image.tmdb.org/t/p/original/adlZgxAudw3ZPA0HUcDzSTKrH8B.jpg",
            "gender": "TV"
        },
        {
            "id": "64",
            "idi": 984303,
            "title": "Dirty Little Secret",
            "language": "en",
            "overview": "17 year-old Lucy who has been painfully isolated from her peers for years, refusing to let anyone near her house in order to hide her family secret – the overwhelming mountain of items filled in every crevice of space in her home. She quietly pl",
            "image": "https://image.tmdb.org/t/p/original/meYRFb7r1aKCYeSyWAQwEd3fPrr.jpg",
            "date": "2022-06-11",
            "background": "https://image.tmdb.org/t/p/original/sJk1wJxhqNEVNnQKzzocjF6gODt.jpg",
            "gender": "TV"
        },
        {
            "id": "65",
            "idi": 335795,
            "title": "Monster High: The Movie",
            "language": "en",
            "overview": "Clawdeen Wolf, half human and half werewolf, has recently started attending Monster High, a school for monsters in all forms. After quickly befriending her classmates Frankie Stein and Draculaura, Clawdeen feels like she has finally found a plac",
            "image": "https://image.tmdb.org/t/p/original/tn3GWm0Erehkpur8PUuYWxGpul5.jpg",
            "date": "2022-10-06",
            "background": "https://image.tmdb.org/t/p/original/sobIeWp1a3saZTBkoRTAf8sfC7J.jpg",
            "gender": "TV"
        },
        {
            "id": "66",
            "idi": 951368,
            "title": "Your Boyfriend Is Mine",
            "language": "en",
            "overview": "Over the objection of his girlfriend, Ben agrees to take a job as the “live in” man servant to a wealthy businesswoman, Amanda, but quickly realizes he has made a deal with the devil, and has put himself and his girlfriend in mortal jeopardy",
            "image": "https://image.tmdb.org/t/p/original/2OOYNZLKjdX8Z5KNyz7zZnHmodJ.jpg",
            "date": "2022-03-19",
            "background": "https://image.tmdb.org/t/p/original/mCAkUizRRIwKMOlne9CIoJ3utSc.jpg",
            "gender": "TV"
        },
        {
            "id": "67",
            "idi": 726684,
            "title": "Miraculous World: Shanghai – The Legend of Ladydragon",
            "language": "fr",
            "overview": "On school break, Marinette heads to Shanghai to meet Adrien. But after arriving, Marinette loses all her stuff, including the Miraculous that allows her to turn into Ladybug!",
            "image": "https://image.tmdb.org/t/p/original/qQ0VKsGRQ2ofAmswGNzZnvC1xPE.jpg",
            "date": "2021-05-15",
            "background": "https://image.tmdb.org/t/p/original/rlNnwObbMu5G2FaOUlacnUIdIIA.jpg",
            "gender": "TV"
        },
        {
            "id": "68",
            "idi": 801335,
            "title": "Girl in the Basement",
            "language": "en",
            "overview": "Sara is a teen girl who is looking forward to her 18th birthday to move away from her controlling father Don. But before she could even blow out the candles, Don imprisons her in the basement of their home.",
            "image": "https://image.tmdb.org/t/p/original/qmddUxRwbsxHa7oEXm4PWh1KZe8.jpg",
            "date": "2021-02-27",
            "background": "https://image.tmdb.org/t/p/original/fvUmnxS9xaUUl0eWygvcA1hPdTV.jpg",
            "gender": "TV"
        },
        {
            "id": "69",
            "idi": 936061,
            "title": "Under Wraps 2",
            "language": "en",
            "overview": "As Marshall, Gilbert and Amy are preparing for her father’s Spooktacular Halloween-themed wedding to his fiancé Carl, plans go awry when they discover that their mummy friend Harold and his beloved Rose may be in danger.",
            "image": "https://image.tmdb.org/t/p/original/y37QvulwOJ1uv0onnDB4ocWEQZn.jpg",
            "date": "2022-09-25",
            "background": "https://image.tmdb.org/t/p/original/1PngAR4KRkKY1dNIelMMUd2M8ti.jpg",
            "gender": "TV"
        },
        {
            "id": "70",
            "idi": 946581,
            "title": "Cruel Instruction",
            "language": "en",
            "overview": "The story of 16-year-old Kayla Adams, whose mother, Karen is advised by the school’s counselor to send Kayla to get treatment at a youth residential treatment center after she gets expelled from school. Kayla arrives at the Utah facility on the ",
            "image": "https://image.tmdb.org/t/p/original/8T43AlhBdkwRSrN3UlYIgKqjWkL.jpg",
            "date": "2022-03-12",
            "background": "https://image.tmdb.org/t/p/original/7ZOmcNRhCqu4xFW0SREqBREIfQ0.jpg",
            "gender": "TV"
        },
        {
            "id": "71",
            "idi": 441168,
            "title": "From Straight A's to XXX",
            "language": "en",
            "overview": "When a change of circumstances leaves Miriam unable to pay her college tuition, she makes a surprising decision: to start performing in adult films, using the pseudonym Belle Knox. Miriam lies to her family and her friends at school, keeping her",
            "image": "https://image.tmdb.org/t/p/original/pv5n66n3J9DzNeEzGymhQ0q2FcS.jpg",
            "date": "2017-02-11",
            "background": "https://image.tmdb.org/t/p/original/3uaD05vhpsjiZ9KHpF2TI2GrXON.jpg",
            "gender": "TV"
        },
        {
            "id": "72",
            "idi": 894205,
            "title": "Werewolf by Night",
            "language": "en",
            "overview": "On a dark and somber night, a secret cabal of monster hunters emerge from the shadows and gather at the foreboding Bloodstone Temple following the death of their leader. In a strange and macabre memorial to the leader’s life, the attendees are t",
            "image": "https://image.tmdb.org/t/p/original/1n2q0Y1pX8PkQh9imqGbNH7Bw4q.jpg",
            "date": "2022-09-25",
            "background": "https://image.tmdb.org/t/p/original/pfAZP7JvTTxqgq7n6A1OYgkAdEW.jpg",
            "gender": "TV"
        },
        {
            "id": "91",
            "idi": 335797,
            "title": "Sing",
            "language": "en",
            "overview": "A koala named Buster recruits his best friend to help him drum up business for his theater by hosting a singing competition.",
            "image": "https://image.tmdb.org/t/p/original/xviEKU073QAzeFRzWDdW9xDHPbB.jpg",
            "date": "2016-11-23",
            "background": "https://image.tmdb.org/t/p/original/59CCw4EtiahW0E5cfTrvdbqPQTo.jpg",
            "gender": "Music"
        },
        {
            "id": "73",
            "idi": 1019345,
            "title": "Shabash Feluda",
            "language": "bn",
            "overview": "Feluda and Topshe travel to Gangtok for their winter holidays at the start of the new year. While eating breakfast at the Bagdogra Airport, they meet a man named Sasadhar Bose, who works for a chemical firm dealing with aromatic perfumes. He tel",
            "image": "https://image.tmdb.org/t/p/original/cjOaxRVZkADV8EoX3IKevKMgK7j.jpg",
            "date": "2023-05-05",
            "background": "https://image.tmdb.org/t/p/original/tL0OAuR9nC3aGl6NTmSDLlBcLIP.jpg",
            "gender": "TV"
        },
        {
            "id": "74",
            "idi": 9288,
            "title": "Dungeons & Dragons: Wrath of the Dragon God",
            "language": "en",
            "overview": "Due to a curse from his former master Profion, Damodar survived his death by Ridley Freeborn as an undead entity in pursuit of an evil artifact for some hundred years, so that he might be capable of unleashing unstoppable destruction on Izmir an",
            "image": "https://image.tmdb.org/t/p/original/m2lMUxyFDi1RXogMffLfQW3CjTE.jpg",
            "date": "2005-09-01",
            "background": "https://image.tmdb.org/t/p/original/eBJDAJmhFVLINV78sB0VkvCsVkB.jpg",
            "gender": "TV"
        },
        {
            "id": "75",
            "idi": 937046,
            "title": "L'oubliée d'Amboise",
            "language": "fr",
            "overview": "A violinist is found dead not far from the tomb of DaVinci, in a suspicious position. Captain of the Orléans research section, Alban Dutertre teams up with Officer Bérénice Amarillo. Alban and Bérénice will have to solve the puzzle.",
            "image": "https://image.tmdb.org/t/p/original/n7Per7QRNDcjTyDg8qHvotOBion.jpg",
            "date": "2022-04-03",
            "background": "https://image.tmdb.org/t/p/original/ggS7TQgu34Lct30MFwNlxVRJOia.jpg",
            "gender": "TV"
        },
        {
            "id": "76",
            "idi": 1093765,
            "title": "A Pinch of Portugal",
            "language": "en",
            "overview": "When a celebrity chef walks off his show, prep cook Anna must step into the spotlight and make the show her own, with the help of her Aussie cameraman and Portuguese location scout.",
            "image": "https://image.tmdb.org/t/p/original/kezARoHkqxe9rwooYs2od1GgdOf.jpg",
            "date": "2023-04-22",
            "background": "https://image.tmdb.org/t/p/original/rLJVkBXLpMFvxU5DXskZWJEm8o7.jpg",
            "gender": "TV"
        },
        {
            "id": "77",
            "idi": 277217,
            "title": "Descendants",
            "language": "en",
            "overview": "A present-day idyllic kingdom where the benevolent teenage son of King Adam and Queen Belle offers a chance of redemption for the troublemaking offspring of Disney's classic villains: Cruella De Vil (Carlos), Maleficent (Mal), the Evil Queen (Ev",
            "image": "https://image.tmdb.org/t/p/original/65DkgHPSLVjgr6IYkpY9Aqqqid5.jpg",
            "date": "2015-07-31",
            "background": "https://image.tmdb.org/t/p/original/wy3ItrIw4DmLFxvFK5LM6FPwdQw.jpg",
            "gender": "TV"
        },
        {
            "id": "78",
            "idi": 506574,
            "title": "Descendants 3",
            "language": "en",
            "overview": "The teenagers of Disney's most infamous villains return to the Isle of the Lost to recruit a new batch of villainous offspring to join them at Auradon Prep.",
            "image": "https://image.tmdb.org/t/p/original/7IRy0iHdaS0JI3ng4ZYlk5gLSFn.jpg",
            "date": "2019-08-02",
            "background": "https://image.tmdb.org/t/p/original/p0boFm5Z1HzO6LHMBuLYUM48iVV.jpg",
            "gender": "TV"
        },
        {
            "id": "79",
            "idi": 1010261,
            "title": "Love at Mariposa Beach",
            "language": "en",
            "overview": "Reeling from a recent break up and career frustration, aspiring food blogger, Claire (Lucia Gomez Robledo), sets out on a journey of self-discovery in Mariposa Beach, Mexico after finding a photo album of her mother’s childhood there.",
            "image": "https://image.tmdb.org/t/p/original/72CeCsHN1cecsNCc1wNQ6NWH3hf.jpg",
            "date": "2023-04-25",
            "background": "https://image.tmdb.org/t/p/original/l08MWAPTH4zNHltT5BNY6CMeBca.jpg",
            "gender": "TV"
        },
        {
            "id": "80",
            "idi": 831410,
            "title": "Bring It On: Cheer Or Die",
            "language": "en",
            "overview": "When a cheer squad practices their routines on Halloween weekend in an abandoned school, they are picked off one by one by an unknown killer.",
            "image": "https://image.tmdb.org/t/p/original/ciRq9QUBpFWNsFKs2opG5tP157.jpg",
            "date": "2022-09-27",
            "background": "https://image.tmdb.org/t/p/original/mYOooABOzWRaFMRWDhUAXiKuTaO.jpg",
            "gender": "TV"
        },
        {
            "id": "81",
            "idi": 671583,
            "title": "Upside-Down Magic",
            "language": "en",
            "overview": "Nory and her best friend Reina enter the Sage Academy for Magical Studies, where Nory’s unconventional powers land her in a class for those with wonky, or “upside-down,” magic. Undaunted, Nory sets out to prove that that upside-down magic can be",
            "image": "https://image.tmdb.org/t/p/original/h9vTJ78h0SASYUxg4jV0AQ00oF2.jpg",
            "date": "2020-07-31",
            "background": "https://image.tmdb.org/t/p/original/vam9VHLZl8tqNwkp1zjEAxIOrkk.jpg",
            "gender": "TV"
        },
        {
            "id": "82",
            "idi": 1041513,
            "title": "Encanto at the Hollywood Bowl",
            "language": "en",
            "overview": "A taped performance of the Encanto Live-to-Film Concert Experience at the Hollywood Bowl. The original cast puts on a miracle of a concert as they sing the favorite songs, accompanied by a full orchestra and 50 person ensemble, and the Hollywood",
            "image": "https://image.tmdb.org/t/p/original/sa3Ku5yNVjp8NloWxJoI9dQjvOi.jpg",
            "date": "2022-12-28",
            "background": "https://image.tmdb.org/t/p/original/tsjXBo4LmzV0Bb9hdrz25tzX5GD.jpg",
            "gender": "Music"
        },
        {
            "id": "83",
            "idi": 555604,
            "title": "Guillermo del Toro's Pinocchio",
            "language": "en",
            "overview": "During the rise of fascism in Mussolini's Italy, a wooden boy brought magically to life struggles to live up to his father's expectations.",
            "image": "https://image.tmdb.org/t/p/original/vx1u0uwxdlhV2MUzj4VlcMB0N6m.jpg",
            "date": "2022-11-09",
            "background": "https://image.tmdb.org/t/p/original/e782pDRAlu4BG0ahd777n8zfPzZ.jpg",
            "gender": "Music"
        },
        {
            "id": "84",
            "idi": 830784,
            "title": "Lyle, Lyle, Crocodile",
            "language": "en",
            "overview": "When the Primm family moves to New York City, their young son Josh struggles to adapt to his new school and new friends. All of that changes when he discovers Lyle — a singing crocodile who loves baths, caviar and great music — living in the att",
            "image": "https://image.tmdb.org/t/p/original/irIS5Tn3TXjNi1R9BpWvGAN4CZ1.jpg",
            "date": "2022-10-07",
            "background": "https://image.tmdb.org/t/p/original/eIeCUHk8q7smdd2KAiPBmceN7QS.jpg",
            "gender": "Music"
        },
        {
            "id": "85",
            "idi": 354912,
            "title": "Coco",
            "language": "en",
            "overview": "Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead f",
            "image": "https://image.tmdb.org/t/p/original/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
            "date": "2017-10-27",
            "background": "https://image.tmdb.org/t/p/original/askg3SMvhqEl4OL52YuvdtY40Yb.jpg",
            "gender": "Music"
        },
        {
            "id": "86",
            "idi": 939210,
            "title": "Blue's Big City Adventure",
            "language": "en",
            "overview": "When Josh gets the opportunity of a lifetime to audition for Rainbow Puppy’s Broadway musical, Josh and Blue skidoo to NYC for the very first time where they meet new friends and discover the magic of music, dance, and following one’s dreams.",
            "image": "https://image.tmdb.org/t/p/original/5JV5nDPMYQLaZz2n0SmxQfMYfLn.jpg",
            "date": "2022-11-18",
            "background": "https://image.tmdb.org/t/p/original/17sIiv4LGapYnyvdpKxA1vozBqY.jpg",
            "gender": "Music"
        },
        {
            "id": "87",
            "idi": 551806,
            "title": "Praise This",
            "language": "en",
            "overview": "When aspiring musical superstar Sam is forced to join her cousin's struggling, underdog praise team in the lead-up to a national championship competition, she sees an opportunity to finally make her dreams come true.",
            "image": "https://image.tmdb.org/t/p/original/twdgFrp9Sd8rb3TdbWFQXAvslrH.jpg",
            "date": "2023-04-07",
            "background": "https://image.tmdb.org/t/p/original/i3GJte6Bf5sbEEVTpQQytAg8ZBE.jpg",
            "gender": "Music"
        },
        {
            "id": "88",
            "idi": 335795,
            "title": "Monster High: The Movie",
            "language": "en",
            "overview": "Clawdeen Wolf, half human and half werewolf, has recently started attending Monster High, a school for monsters in all forms. After quickly befriending her classmates Frankie Stein and Draculaura, Clawdeen feels like she has finally found a plac",
            "image": "https://image.tmdb.org/t/p/original/tn3GWm0Erehkpur8PUuYWxGpul5.jpg",
            "date": "2022-10-06",
            "background": "https://image.tmdb.org/t/p/original/sobIeWp1a3saZTBkoRTAf8sfC7J.jpg",
            "gender": "Music"
        },
        {
            "id": "89",
            "idi": 479197,
            "title": "Melody Makers",
            "language": "en",
            "overview": "Melody Maker Magazine's Chief Contributing Photographer(1965-1975), Barrie Wentzell tells the story of the rise and fall of the magazine, which marked the end to a style of rock n' roll journalism that no longer exit's today.",
            "image": "https://image.tmdb.org/t/p/original/z521Q2X94hgLUtqP1HAbZqxhUu5.jpg",
            "date": "2019-12-17",
            "background": "https://image.tmdb.org/t/p/originalnull",
            "gender": "Music"
        },
        {
            "id": "90",
            "idi": 1023803,
            "title": "The Hip Hop Nutcracker",
            "language": "en",
            "overview": "Features Rev Run as he brings audiences on a hip-hop reimagining of The Nutcracker ballet set in NYC.",
            "image": "https://image.tmdb.org/t/p/original/iqOGxcKViTtU7pwC24xUb1bDslw.jpg",
            "date": "2022-11-25",
            "background": "https://image.tmdb.org/t/p/original/3t0DcVPuW9JRtc1CWnh1ktCKrrO.jpg",
            "gender": "Music"
        },
        {
            "id": "92",
            "idi": 614934,
            "title": "Elvis",
            "language": "en",
            "overview": "The life story of Elvis Presley as seen through the complicated relationship with his enigmatic manager, Colonel Tom Parker.",
            "image": "https://image.tmdb.org/t/p/original/qBOKWqAFbveZ4ryjJJwbie6tXkQ.jpg",
            "date": "2022-06-22",
            "background": "https://image.tmdb.org/t/p/original/rLo9T9jEg67UZPq3midjLnTUYYi.jpg",
            "gender": "Music"
        },
        {
            "id": "93",
            "idi": 817758,
            "title": "TÁR",
            "language": "en",
            "overview": "Renowned musician Lydia Tár is days away from recording the symphony that will elevate her career.  However, Lydia's elaborate facade begins to unravel, revealing dirty secrets and the corrosive nature of power.",
            "image": "https://image.tmdb.org/t/p/original/dRVAlaU0vbG6hMf2K45NSiIyoUe.jpg",
            "date": "2022-09-23",
            "background": "https://image.tmdb.org/t/p/original/fwnXTIWQl1Ky6CgcWMBhkn9uV3g.jpg",
            "gender": "Music"
        },
        {
            "id": "94",
            "idi": 244786,
            "title": "Whiplash",
            "language": "en",
            "overview": "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
            "image": "https://image.tmdb.org/t/p/original/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
            "date": "2014-10-10",
            "background": "https://image.tmdb.org/t/p/original/5h8VtV4oh2qkO8Iqz7gypIYJPAr.jpg",
            "gender": "Music"
        },
        {
            "id": "95",
            "idi": 136799,
            "title": "Trolls",
            "language": "en",
            "overview": "From the creators of Shrek comes the most smart, funny, irreverent animated comedy of the year, DreamWorks' Trolls. This holiday season, enter a colorful, wondrous world populated by hilariously unforgettable characters and discover the story of",
            "image": "https://image.tmdb.org/t/p/original/zKu5MNy9QW1a5ZHgv7iAp3kRZpE.jpg",
            "date": "2016-10-13",
            "background": "https://image.tmdb.org/t/p/original/gWCWHybWuVg3GmZpdY8qWGb85HR.jpg",
            "gender": "Music"
        },
        {
            "id": "96",
            "idi": 446893,
            "title": "Trolls World Tour",
            "language": "en",
            "overview": "Queen Poppy and Branch make a surprising discovery — there are other Troll worlds beyond their own, and their distinct differences create big clashes between these various tribes. When a mysterious threat puts all of the Trolls across the land i",
            "image": "https://image.tmdb.org/t/p/original/7W0G3YECgDAfnuiHG91r8WqgIOe.jpg",
            "date": "2020-03-11",
            "background": "https://image.tmdb.org/t/p/original/ybGEvB6725PkVuUfEo2txLGRwTj.jpg",
            "gender": "Music"
        },
        {
            "id": "97",
            "idi": 1022256,
            "title": "Selena Gomez: My Mind & Me",
            "language": "en",
            "overview": "After years in the limelight, Selena Gomez achieves unimaginable stardom. But just as she reaches a new peak, an unexpected turn pulls her into darkness. This uniquely raw and intimate documentary spans her six-year journey into a new light.",
            "image": "https://image.tmdb.org/t/p/original/oMpsswJv8x4vnOnIKqs4xJs2Kn3.jpg",
            "date": "2022-11-04",
            "background": "https://image.tmdb.org/t/p/original/8SKOYP0ukOCAixubONgTpWcMCKA.jpg",
            "gender": "Music"
        },
        {
            "id": "98",
            "idi": 470878,
            "title": "I Can Only Imagine",
            "language": "en",
            "overview": "10-year-old Bart Millard lives with his mother and abusive father Arthur in Texas. One day his mother drops him off at a Christian camp where he meets Shannon. Upon his return from camp, Bart finds his mother has left and movers are removing her",
            "image": "https://image.tmdb.org/t/p/original/veZszwMZu8d3WMU6TJX9sV5w1Y4.jpg",
            "date": "2018-02-14",
            "background": "https://image.tmdb.org/t/p/original/AjtQdUX41skfo8tthtrnJZI9bXV.jpg",
            "gender": "Music"
        },
        {
            "id": "99",
            "idi": 1677,
            "title": "Ray",
            "language": "en",
            "overview": "Born on a sharecropping plantation in Northern Florida, Ray Charles went blind at seven. Inspired by a fiercely independent mom who insisted he make his own way, He found his calling and his gift behind a piano keyboard. Touring across the South",
            "image": "https://image.tmdb.org/t/p/original/tSPC7sO2XYNL9QcMmK88tuUALL5.jpg",
            "date": "2004-10-29",
            "background": "https://image.tmdb.org/t/p/original/yDactKFWsgN6FMWW0kYU7AXhZA9.jpg",
            "gender": "Music"
        },
        {
            "id": "100",
            "idi": 415283,
            "title": "Pop in Q",
            "language": "ja",
            "overview": "The story begins the day before the graduation ceremony. Five middle school girls each are preoccupied with their real everyday lives. These girls meet each other in a fantasy world after being sent there through a sudden occurrence. There, they",
            "image": "https://image.tmdb.org/t/p/original/pk3Q0U7dh3wf3c3J3cagqz0zUE9.jpg",
            "date": "2016-12-23",
            "background": "https://image.tmdb.org/t/p/original/xWRX7tuNC9bNmOW8bezZYfW0zNE.jpg",
            "gender": "Music"
        },
        {
            "id": "101",
            "idi": 88,
            "title": "Dirty Dancing",
            "language": "en",
            "overview": "Expecting the usual tedium that accompanies a summer in the Catskills with her family, 17-year-old Frances 'Baby' Houseman is surprised to find herself stepping into the shoes of a professional hoofer—and unexpectedly falling in love.",
            "image": "https://image.tmdb.org/t/p/original/9Jw6jys7q9gjzVX5zm1z0gC8gY9.jpg",
            "date": "1987-08-21",
            "background": "https://image.tmdb.org/t/p/original/6iDQCBUSZKzY8Rnu8ECwl2gXcfG.jpg",
            "gender": "Music"
        },
        {
            "id": "104",
            "idi": 640146,
            "title": "Ant-Man and the Wasp: Quantumania",
            "language": "en",
            "overview": "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on ",
            "image": "https://image.tmdb.org/t/p/original/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
            "date": "2023-02-15",
            "background": "https://image.tmdb.org/t/p/original/8YFL5QQVPy3AgrEQxNYVSgiPEbe.jpg",
            "gender": "Trending"
        },
        {
            "id": "105",
            "idi": 502356,
            "title": "The Super Mario Bros. Movie",
            "language": "en",
            "overview": "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find",
            "image": "https://image.tmdb.org/t/p/original/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
            "date": "2023-04-05",
            "background": "https://image.tmdb.org/t/p/original/iJQIbOPm81fPEGKt5BPuZmfnA54.jpg",
            "gender": "Trending"
        },
        {
            "id": "106",
            "idi": 868759,
            "title": "Ghosted",
            "language": "en",
            "overview": "Salt-of-the-earth Cole falls head over heels for enigmatic Sadie — but then makes the shocking discovery that she’s a secret agent. Before they can decide on a second date, Cole and Sadie are swept away on an international adventure to save the ",
            "image": "https://image.tmdb.org/t/p/original/liLN69YgoovHVgmlHJ876PKi5Yi.jpg",
            "date": "2023-04-21",
            "background": "https://image.tmdb.org/t/p/original/b9UCfDzwiWw7mIFsIQR9ZJUeh7q.jpg",
            "gender": "Trending"
        },
        {
            "id": "107",
            "idi": 76600,
            "title": "Avatar: The Way of Water",
            "language": "en",
            "overview": "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and",
            "image": "https://image.tmdb.org/t/p/original/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
            "date": "2022-12-14",
            "background": "https://image.tmdb.org/t/p/original/ovM06PdF3M8wvKb06i4sjW3xoww.jpg",
            "gender": "Trending"
        },
        {
            "id": "108",
            "idi": 934433,
            "title": "Scream VI",
            "language": "en",
            "overview": "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.",
            "image": "https://image.tmdb.org/t/p/original/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg",
            "date": "2023-03-08",
            "background": "https://image.tmdb.org/t/p/original/44immBwzhDVyjn87b3x3l9mlhAD.jpg",
            "gender": "Trending"
        },
        {
            "id": "109",
            "idi": 594767,
            "title": "Shazam! Fury of the Gods",
            "language": "en",
            "overview": "Billy Batson and his foster siblings, who transform into superheroes by saying \"Shazam!\", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.",
            "image": "https://image.tmdb.org/t/p/original/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg",
            "date": "2023-03-15",
            "background": "https://image.tmdb.org/t/p/original/wybmSmviUXxlBmX44gtpow5Y9TB.jpg",
            "gender": "Trending"
        },
        {
            "id": "110",
            "idi": 82856,
            "title": "Netflix Edidition",
            "language": "en",
            "overview": "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
            "image": "https://image.tmdb.org/t/p/original/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
            "date": "2020",
            "background": "https://image.tmdb.org/t/p/original/6Lw54zxm6BAEKJeGlabyzzR5Juu.jpg",
            "gender": "Trending"
        },
        {
            "id": "111",
            "idi": 700391,
            "title": "65",
            "language": "en",
            "overview": "65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth must fend off dinosaurs and reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.",
            "image": "https://image.tmdb.org/t/p/original/rzRb63TldOKdKydCvWJM8B6EkPM.jpg",
            "date": "2023-03-02",
            "background": "https://image.tmdb.org/t/p/original/eSVu1FvGPy86TDo4hQbpuHx55DJ.jpg",
            "gender": "Trending"
        },
        {
            "id": "112",
            "idi": 603692,
            "title": "John Wick: Chapter 4",
            "language": "en",
            "overview": "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old frien",
            "image": "https://image.tmdb.org/t/p/original/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
            "date": "2023-03-22",
            "background": "https://image.tmdb.org/t/p/original/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
            "gender": "Trending"
        },
        {
            "id": "113",
            "idi": 85937,
            "title": "Netflix Edidition",
            "language": "ja",
            "overview": "It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself",
            "image": "https://image.tmdb.org/t/p/original/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
            "date": "2020",
            "background": "https://image.tmdb.org/t/p/original/nTvM4mhqNlHIvUkI1gVnW6XP7GG.jpg",
            "gender": "Trending"
        },
        {
            "id": "114",
            "idi": 713704,
            "title": "Evil Dead Rise",
            "language": "en",
            "overview": "Two sisters find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
            "image": "https://image.tmdb.org/t/p/original/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg",
            "date": "2023-04-12",
            "background": "https://image.tmdb.org/t/p/original/7bWxAsNPv9CXHOhZbJVlj2KxgfP.jpg",
            "gender": "Trending"
        },
        {
            "id": "115",
            "idi": 948713,
            "title": "The Last Kingdom: Seven Kings Must Die",
            "language": "en",
            "overview": "In the wake of King Edward's death, Uhtred of Bebbanburg and his comrades adventure across a fractured kingdom in the hopes of uniting England at last.",
            "image": "https://image.tmdb.org/t/p/original/7yyFEsuaLGTPul5UkHc5BhXnQ0k.jpg",
            "date": "2023-04-14",
            "background": "https://image.tmdb.org/t/p/original/xwA90BwZXTh8ke3CVsQlj8EOkFr.jpg",
            "gender": "Trending"
        },
        {
            "id": "116",
            "idi": 739405,
            "title": "Operation Fortune: Ruse de Guerre",
            "language": "en",
            "overview": "Special agent Orson Fortune and his team of operatives recruit one of Hollywood's biggest movie stars to help them on an undercover mission when the sale of a deadly new weapons technology threatens to disrupt the world order.",
            "image": "https://image.tmdb.org/t/p/original/uo7vWfQUlVwueYTDRicXOJa8Oow.jpg",
            "date": "2023-01-04",
            "background": "https://image.tmdb.org/t/p/original/7TdVWAO7vV9j1OLDq1hQJS3pb4U.jpg",
            "gender": "Trending"
        },
        {
            "id": "117",
            "idi": 677179,
            "title": "Creed III",
            "language": "en",
            "overview": "After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damian Anderson, resurfaces after serving a long sentence in prison, he is eager to prove th",
            "image": "https://image.tmdb.org/t/p/original/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg",
            "date": "2023-03-01",
            "background": "https://image.tmdb.org/t/p/original/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg",
            "gender": "Trending"
        },
        {
            "id": "118",
            "idi": 203857,
            "title": "Netflix Edidition",
            "language": "en",
            "overview": "In the midst of an international crisis, a career diplomat lands in a high-profile job she’s unsuited for, with tectonic implications for her marriage and her political future.",
            "image": "https://image.tmdb.org/t/p/original/cOKXV0FalCYixNmZYCfHXgyQ0VX.jpg",
            "date": "2020",
            "background": "https://image.tmdb.org/t/p/original/euzOZte7gh2MvocsMbQlv0IoKFI.jpg",
            "gender": "Trending"
        },
        {
            "id": "119",
            "idi": 447365,
            "title": "Guardians of the Galaxy Volume 3",
            "language": "en",
            "overview": "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardian",
            "image": "https://image.tmdb.org/t/p/original/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
            "date": "2023-05-03",
            "background": "https://image.tmdb.org/t/p/original/dQObIWkxfzKEDhtjOSoFnyCVgt0.jpg",
            "gender": "Trending"
        },
        {
            "id": "120",
            "idi": 916224,
            "title": "Suzume",
            "language": "ja",
            "overview": "Suzume, 17, lost her mother as a little girl. On her way to school, she meets a mysterious young man. But her curiosity unleashes a calamity that endangers the entire population of Japan, and so Suzume embarks on a journey to set things right.",
            "image": "https://image.tmdb.org/t/p/original/vIeu8WysZrTSFb2uhPViKjX9EcC.jpg",
            "date": "2022-11-11",
            "background": "https://image.tmdb.org/t/p/original/ceYZCBfwbBwSpGJ6PapNVw5jqLG.jpg",
            "gender": "Trending"
        },
        {
            "id": "121",
            "idi": 726759,
            "title": "Tetris",
            "language": "en",
            "overview": "In 1988, American video game salesman Henk Rogers discovers the video game Tetris. When he sets out to bring the game to the world, he enters a dangerous web of lies and corruption behind the Iron Curtain.",
            "image": "https://image.tmdb.org/t/p/original/4F2QwCOYHJJjecSvdOjStuVLkpu.jpg",
            "date": "2023-03-15",
            "background": "https://image.tmdb.org/t/p/original/4avmIRBBOs9b4DKoenf8SWWJJP7.jpg",
            "gender": "Trending"
        },
        {
            "id": "122",
            "idi": 1068141,
            "title": "Mighty Morphin Power Rangers: Once & Always",
            "language": "en",
            "overview": "After tragedy strikes, an unlikely young hero takes her rightful place among the Power Rangers to face off against the team's oldest archnemesis.",
            "image": "https://image.tmdb.org/t/p/original/vc87upO8vcAGj9OmgH3AIz6ikKB.jpg",
            "date": "2023-04-19",
            "background": "https://image.tmdb.org/t/p/original/vcNXzOfACCXZA7vb8SNde0LUC9o.jpg",
            "gender": "Trending"
        },
        {
            "id": "123",
            "idi": 154385,
            "title": "Netflix Edidition",
            "language": "en",
            "overview": "A road rage incident between two strangers — a failing contractor and an unfulfilled entrepreneur — sparks a feud that brings out their darkest impulses.",
            "image": "https://image.tmdb.org/t/p/original/4b4v7RnPhNyPEaVGFarEuo74r8W.jpg",
            "date": "2020",
            "background": "https://image.tmdb.org/t/p/original/u7OpeS4eckBSR1wFxFTuyy3FjHE.jpg",
            "gender": "Trending"
        }
    ]
